<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-28T20:31:30Z" name="All Test Suite" finished-at="2021-05-28T20:32:11Z" duration-ms="41065">
    <groups>
    </groups>
    <test started-at="2021-05-28T20:31:30Z" name="C:/Users/R/Documents/IdeaProjects/Examen2ParcialExercise2" finished-at="2021-05-28T20:32:11Z" duration-ms="41065">
      <class name="Exercise2">
        <test-method is-config="true" signature="setUrl()[pri:0, instance:Exercise2@63355449]" started-at="2021-05-28T20:31:30Z" name="setUrl" finished-at="2021-05-28T20:31:36Z" duration-ms="5474" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUrl -->
        <test-method signature="emptyCredentials()[pri:1, instance:Exercise2@63355449]" started-at="2021-05-28T20:31:36Z" name="emptyCredentials" finished-at="2021-05-28T20:31:40Z" duration-ms="4379" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Exercise2.emptyCredentials(Exercise2.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyCredentials -->
        <test-method signature="invalidCredentials()[pri:2, instance:Exercise2@63355449]" started-at="2021-05-28T20:31:40Z" name="invalidCredentials" finished-at="2021-05-28T20:31:45Z" duration-ms="4533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredentials -->
        <test-method signature="verifyButtonReset()[pri:3, instance:Exercise2@63355449]" started-at="2021-05-28T20:31:45Z" name="verifyButtonReset" finished-at="2021-05-28T20:31:49Z" duration-ms="4128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyButtonReset -->
        <test-method signature="UserInvalid()[pri:4, instance:Exercise2@63355449]" started-at="2021-05-28T20:31:49Z" name="UserInvalid" finished-at="2021-05-28T20:31:54Z" duration-ms="4945" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserInvalid -->
        <test-method signature="PasswordInvalid()[pri:5, instance:Exercise2@63355449]" started-at="2021-05-28T20:31:54Z" name="PasswordInvalid" finished-at="2021-05-28T20:32:01Z" duration-ms="6673" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PasswordInvalid -->
        <test-method signature="LoginSuccefull()[pri:6, instance:Exercise2@63355449]" started-at="2021-05-28T20:32:01Z" name="LoginSuccefull" finished-at="2021-05-28T20:32:06Z" duration-ms="5291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccefull -->
        <test-method signature="VerifyLoggedOut()[pri:7, instance:Exercise2@63355449]" started-at="2021-05-28T20:32:06Z" name="VerifyLoggedOut" finished-at="2021-05-28T20:32:11Z" duration-ms="5610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoggedOut -->
        <test-method is-config="true" signature="endSesion()[pri:0, instance:Exercise2@63355449]" started-at="2021-05-28T20:32:11Z" name="endSesion" finished-at="2021-05-28T20:32:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSesion -->
      </class> <!-- Exercise2 -->
    </test> <!-- C:/Users/R/Documents/IdeaProjects/Examen2ParcialExercise2 -->
  </suite> <!-- All Test Suite -->
</testng-results>
