<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-J8IPJOP" failures="1" tests="9" name="C:/Users/R/Documents/IdeaProjects/Examen2doParcialExercise4" time="87.575" errors="0" timestamp="28 May 2021 21:42:55 GMT">
  <testcase classname="Exercise4Class1" name="LoginSuccefull" time="11.285"/>
  <testcase classname="Exercise4Class1" name="UserInvalid" time="9.08"/>
  <testcase classname="Exercise4Class1" name="VerifyInputValid" time="6.71"/>
  <testcase classname="Exercise4Class1" name="VerifyLoggedOut" time="10.32"/>
  <testcase classname="Exercise4Class1" name="invalidCredentials" time="9.241"/>
  <testcase classname="Exercise4Class1" name="verifyButtonReset" time="9.189"/>
  <testcase classname="Exercise4Class1" name="verifyEmptyField" time="11.04"/>
  <testcase classname="Exercise4Class2" name="VerifyInputValid" time="10.981"/>
  <testcase classname="Exercise4Class2" name="verifyEmptyField" time="9.654">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Exercise4Class2.verifyEmptyField(Exercise4Class2.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- verifyEmptyField -->
  <testcase classname="Exercise4Class1" name="emptyCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- emptyCredentials -->
  <testcase classname="Exercise4Class1" name="verifyForm" time="0.0">
    <ignored/>
  </testcase> <!-- verifyForm -->
  <testcase classname="Exercise4Class1" name="PasswordInvalid" time="0.0">
    <ignored/>
  </testcase> <!-- PasswordInvalid -->
  <testcase classname="Exercise4Class2" name="verifyForm" time="0.0">
    <ignored/>
  </testcase> <!-- verifyForm -->
</testsuite> <!-- C:/Users/R/Documents/IdeaProjects/Examen2doParcialExercise4 -->
